const ART = [
  {"title": "Owl",
   "filename": "owl.txt",
   "credit_text": "Donovan Bake",
   "credit_url": "https://www.asciiart.eu/animals/birds-land"},
  {"title": "Earth",
   "filename": "earth.txt",
   "credit_text": "jgs",
   "credit_url": "https://www.asciiart.eu/space/planets"},
  {"title": "Cat",
   "filename": "CatBox.txt",
   "credit_text": "HJS",
   "credit_url": "https://www.asciiart.eu/animals/cats"},
  {"title": "Keyboard",
   "filename": "keyboard.txt",
   "credit_text": "hjw",
   "credit_url": "https://www.asciiart.eu/music/musical-instruments"},
  {"title": "Mushroom",
   "filename": "mushroom.txt",
   "credit_text": "itz",
   "credit_url": "https://www.asciiart.eu/plants/mushroom"},
];
