const ART = [
  {"title": "Owl",
   "filename": "owl.txt",
   "credit_text": "Donovan Bake",
   "credit_url": "https://www.asciiart.eu/animals/birds-land"},
  {"title": "Earth",
   "filename": "earth.txt",
   "credit_text": "jgs",
   "credit_url": "https://www.asciiart.eu/space/planets"},
  {"title":"Star",
    "filename":"star.txt",
   "credit_text":"hjw",
   "credit_url":"https://www.asciiart.eu/space/stars"
  },
  {"title": "rat",
   "filename": "rat.txt",
   "credit_text": "DNE",
   "credit_url": "https://www.asciiart.eu/animals/rodents/other"},
  {"title": "Einstein",
   "filename": "einstein.txt",
   "credit_text": "jgs",
   "credit_url": "https://www.asciiart.eu/people/famous/albert-einstein"},
  {"title": "Cat",
   "filename": "CatBox.txt",
   "credit_text": "HJS",
   "credit_url": "https://www.asciiart.eu/animals/cats"},
  {"title": "Keyboard",
   "filename": "keyboard.txt",
   "credit_text": "hjw",
   "credit_url": "https://www.asciiart.eu/music/musical-instruments"},
  {"title": "Eeyore",
   "filename": "eeyore-art.txt",
   "credit_text": "jgs",
   "credit_url": "asciiart.eu/books/winnie-the-pooh"},
  {"title": "Statue of Liberty",
   "filename": "statueOfLiberty.txt",
   "credit_text": "Joan Stark",
   "credit_url": "https://www.asciiart.eu/buildings-and-places/monuments/statue-of-liberty"},
  {"title": "Dice",
   "filename": "dice.txt",
   "credit_text": "Joan G Stark",
   "credit_url": "https://www.asciiart.eu/miscellaneous/dice"}
];
