const ART = [
  {"title": "Owl",
   "filename": "owl.txt",
   "credit_text": "Donovan Bake",
   "credit_url": "https://www.asciiart.eu/animals/birds-land"},
  {"title": "Earth",
   "filename": "earth.txt",
   "credit_text": "jgs",
   "credit_url": "https://www.asciiart.eu/space/planets"},
  {"title": "rat",
   "filename": "rat.txt",
   "credit_text": "DNE",
   "credit_url": "https://www.asciiart.eu/animals/rodents/other"},
  {"title": "Einstein",
   "filename": "einstein.txt",
   "credit_text": "jgs",
   "credit_url": "https://www.asciiart.eu/people/famous/albert-einstein"},
  {"title": "Cat",
   "filename": "CatBox.txt",
   "credit_text": "HJS",
   "credit_url": "https://www.asciiart.eu/animals/cats"},
  {"title": "Keyboard",
   "filename": "keyboard.txt",
   "credit_text": "hjw",
   "credit_url": "https://www.asciiart.eu/music/musical-instruments"},
  {"title": "Statue of Liberty",
   "filename": "statueOfLiberty.txt",
   "credit_text": "Joan Stark",
   "credit_url": "https://www.asciiart.eu/buildings-and-places/monuments/statue-of-liberty"},
];
